config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only:%i{show edit update destroy}
  def index
    @posts = Post.order(id: :asc)

  end

  def show
    # @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create!(post_params)
    redirect_to post
  end

  def edit
    # @post = Post.find(params[:id])
  end

  def update
    # post = Post.find(params[:id])
    @post.update!(post_params)
    redirect_to @post
  end

  def destroy
    # post = Post.find(params[:id])
    @post.destroy!
    redirect_to root_path
  end

  # Privateメソッド
  private

  def set_post
    @post = Post.find(params[:id])

  end


  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    user = User.create!(user_params)
    redirect_to user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to user
  end

  private
  def user_params
    params.require(:user).permit(:name, :age)

  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<%= link_to "投稿一覧", posts_path %> <%= link_to "新規投稿", new_post_path %>
<%= link_to "ユーザー一覧", users_path %> <%= link_to "ユーザー新規登録", new_user_path %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SyncaPortal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/header" %>
    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <div>
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content, "内容" %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.submit button_value %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>編集</h1>
<%= render "form", button_value: "更新"  %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<table>
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">タイトル</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each.with_index(1) do |post, i| %>
      <tr>
        <th scope="row"><%= i %></th>
        <td><%= post.title %></td>
        <td>
          <%= link_to "詳細", post %>
          <%= link_to "編集", edit_post_path(post) %>
          <%= link_to "削除", post, method: :delete, data: { confirm: "削除しますか?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= render "form", button_value: "投稿" %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
<p>タイトル <%= @post.title %></p>
<p>内容 <%= @post.content %></p>

app/views/users/edit.html.erb
<h1>更新</h1>
<%= form_with model: @user, local: true do |f| %>
  <div>
    <%= f.label :name, "お名前：" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :age, "年齢：" %>
    <%= f.text_field :age %>
  </div>
  <div>
    <%= f.submit "送信" %> <button><%= link_to "戻る", users_path %></button>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<table>
  <thead>
    <tr>
      <th scope="col">名前</th>
      <th scope="col">年齢</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td>
          <%= link_to "削除", user_path(user), method: :delete, data: {confirm: "削除しますか?"} %>
          <%= link_to "編集", edit_user_path(user) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @user, local: true do |f| %>
  <div>
    <%= f.label :name, "お名前" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :age, "年齢：" %>
    <%= f.text_field :age %>
  </div>
  <div>
    <%= f.submit "送信" %>
  </div>

<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>
  <p>お名前：<%= @user.name %></p>
  <p>年齢：<%= @user.age %></p>
<%= link_to "戻る", users_path %>